import { Patient } from './patient.model';

export const PATIENTS: Patient[] = [
  {
    id: 1,
    name: 'Alberto Flores',
    status: 'Ativo',
    diagnosis: '-',
    medicine: '-',
    healthInsurance: 'AMIL',
    lastRequest: '01/01/2024',
  },
  {
    id: 2,
    name: 'Bernardo Albuquerque',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'UNIMED NACIONAL',
    healthInsurance: 'AMIL',
    lastRequest: '01/01/2024',
  },
  {
    id: 3,
    name: 'César Augusto Nunes',
    status: 'Ativo',
    diagnosis: 'Artrite Psoriásica',
    medicine: 'Rinvoq',
    healthInsurance: 'UNIMED BH',
    lastRequest: '01/01/2024',
  },
  {
    id: 4,
    name: 'Diadora Cristina Marques',
    status: 'Ativo',
    diagnosis: 'Espondilite Anquilosante',
    medicine: 'Humira',
    healthInsurance: 'COPASA',
    lastRequest: '01/01/2024',
  },
  {
    id: 5,
    name: 'Eliana Schmutz Cristóvão',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'Orencia',
    healthInsurance: 'IPSEMG',
    lastRequest: '01/01/2024',
  },
  {
    id: 6,
    name: 'Fernanda Valadares Beltrão',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'Orencia',
    healthInsurance: 'FUNDAFFEMG',
    lastRequest: '01/01/2024',
  },
  {
    id: 7,
    name: 'Gustavo Gutierrez Ramos',
    status: 'Ativo',
    diagnosis: 'Asma Grave',
    medicine: 'Orencia',
    healthInsurance: 'CEMIG Saúde',
    lastRequest: '01/01/2024',
  },
  {
    id: 8,
    name: 'Hélio Dantas Gonçalves',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'Orencia',
    healthInsurance: 'Comissão Nacional de Emergência',
    lastRequest: '01/01/2024',
  },
  {
    id: 9,
    name: 'indiara Neves Astuto',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'Orencia',
    healthInsurance: 'Associação Mineria do Ministério',
    lastRequest: '01/01/2024',
  },
  {
    id: 10,
    name: 'Júlio César Sampaio Castro',
    status: 'Ativo',
    diagnosis: 'Artrite Reumatoide',
    medicine: 'Orencia',
    healthInsurance: 'Fundo de Saúde do Exército',
    lastRequest: '01/01/2024',
  },
];
